spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: azanovskiy04@gmail.com
    password: zgwbfusmvbzoajdv # The generated app password without spaces
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: Thoughts API
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # can be none, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
file:
  upload-dir: C:/Users/argoa/Desktop/projects/edu internship/thoughts_api/images/

